- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: apt update upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: apt install
  apt:
    name:
      # 日本語入力を可能にする
      - language-pack-ja
      # == pyenvのインストールに必要 ==
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - git
      # Nginx
      - nginx

- name: Create group
  group:
    name: "{{ group }}"

- name: pyenvをgit clone
  git:
    repo: "git://github.com/yyuu/pyenv.git"
    dest: "{{ pyenv_path }}"
    force: true

- name: pyenvのパーミッション変更(pyenv init時に書き込みが行われるため)
  file:
    path: "{{ pyenv_path }}"
    state: directory
    group: "{{ group }}"
    recurse: yes
    mode: 0777

- name: 全てのユーザにpyenvを有効化
  blockinfile:
    path: "/etc/profile.d/pyenv.sh"
    create: yes
    mode: 0775
    block: |
      export PYENV_ROOT="{{ pyenv_path }}"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- name: Python{{ python_version }}インストール確認(pyenv)
  shell: bash -lc "pyenv versions | grep {{ python_version }}"
  register: pyenv_version
  ignore_errors: yes
  changed_when: false

- name: pyenv install {{ python_version }}
  shell: bash -lc "pyenv install {{ python_version }}"
  when: pyenv_version is failed

- name: pyenv global {{ python_version }}
  shell: bash -lc "pyenv global {{ python_version }}"

- name: upgrade pip
  shell: bash -lc "pip install --upgrade pip"

- name: install pipenv
  shell: bash -lc "pip install pipenv"

- name: install uWSGI
  shell: bash -lc "pip install uWSGI"

- name: uWSGI用のディレクトリ作成
  file:
    path: /var/log/uwsgi
    state: directory
    group: "{{ group }}"
    mode: 0777

- name: nginxのデフォルト設定ファイル存在確認
  stat:
    path: /etc/nginx/sites-enabled/default
  register: link

- name: デフォルト設定のシンボリックリンクを削除(port:80の重複を避けるため)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: link is success
