- name: install Nginx
  apt:
    name: nginx

- name: nginxのデフォルト設定ファイル存在確認
  stat:
    path: "{{ nginx_default_path }}"
  register: link

- name: デフォルト設定のシンボリックリンクを削除(port:80の重複を避けるため)
  file:
    path: "{{ nginx_default_path }}"
    state: absent
  when: link is success

- name: create nginx conf
  template:
    src: ./flask_app.conf.j2
    dest: "{{ nginx_default_conf_path }}"
    mode: 0111
