#######################################
# 全てのホスト、タスクにて使用される変数
#######################################

# Linuxのグループ名
group: covid19
# 使用するPythonバージョン
python_version: 3.8.5
# Pyenvのトップディレクトリ
pyenv_path: /usr/local/bin/.pyenv
# PyenvのPythonパス
pyenv_python_path: "/usr/local/bin/.pyenv/shims/python"
# uWSGI
uwsgi_path: "/usr/local/bin/.pyenv/shims/uwsgi"
uwsgi_service_path: "/etc/systemd/system/uwsgi.service"
uwsgi_log_directory: "/var/log/uwsgi"
uwsgi_log_file_path: "{{ uwsgi_log_directory }}/uwsgi.log"
# Nginx
nginx_default_conf_path : "/etc/nginx/conf.d/flask_app.conf"
nginx_default_path: "/etc/nginx/sites-enabled/default"

# 'project_directory'はホスト毎に変更される
db_file_path: "{{ project_directory }}/sqlite3.db"
cron_app_directory: "{{ project_directory }}/cron"
cron_script_path: "{{ cron_app_directory }}/run.py"
flask_app_directory: "{{ project_directory }}/flask_app"
flask_app_uwsgi_ini_path: "{{ flask_app_directory }}/uwsgi.ini"

# ウェブアプリを公開するIPアドレスもしくはドメイン(Twitterカードにて使用する"og:image"は絶対パスのみ使用できるため)
flask_app_domain: "takowasa-covid19.click"

# サイトの説明に用いる、作者のツイッターアカウント https://twitter.com/XXXXXX 部分
twitter_user_name: "yanagi_1989"
