- hosts: all
  become: yes
  vars_files:
    - vars/common.yml
  roles:
    - common

- hosts: local
  become: yes
  vars_files:
    - vars/common.yml
  vars:
    user: "vagrant"
  roles:
    - local
